### ISSUE TITLE
Implementing Queues & Locking Mechanisms for Intertask Communication in FreeRTOS

### ISSUE THREAD

**Issue by atharvdesai1996** [cu-ecen-5013/final-project-atharvdesai1996#10]
ToDo: Implementing Queues & Locking Mechanism for intertask communication in FreeRTOS Application

DoD:  These tools will be required to be implemented so that the TMP-102 readings and Fingerprint Matched Strings can be sent through the common UART port of Tiva to the BeagleBone Server

**Comment by atharvdesai1996** [comment]
Integrating TMP102 code in my freeRTOS application

**Comment by atharvdesai1996** [comment]
I successfully integrated TMP102 sensor and Fingerprint sensor with my TIVA Board 1294xl. However I faced a number of Issues and have shared some of the **Debugging scenarios** below:

**Comment by atharvdesai1996** [comment]
**Debugging Option 1**

--> Checked for  all the libraries and header files

--> Also, I tried to incorporate relevant files in ARM Linker and ARM Compiler Options as shared in the screenshot below

![filepath](https://user-images.githubusercontent.com/49723941/80284174-1b770980-86da-11ea-9942-62b835ee1d0d.JPG)
![include](https://user-images.githubusercontent.com/49723941/80284175-1ca83680-86da-11ea-84fb-097445d1b3fc.JPG)

**Comment by atharvdesai1996** [comment]
Debugging Option 2:

-->  Since my UART 3 was acting as an interface for fingerprint sensor and this UART 3 was working at 115200 baud rate, I thought of changing the fingerprint sensor Baud rate 

--> As mentioned in its Adtech datasheet, its default baud rate was 9600. I tried to change the baud rate by sending the packet to fingerprint sensor but the problem I realized was that the sending packet to change the baudrate needed to to transmitted at 9600. It was like a deadlock for me ;-)


![fp_data](https://user-images.githubusercontent.com/49723941/80284310-fe8f0600-86da-11ea-9cc3-612346580629.JPG)

**Comment by atharvdesai1996** [comment]
**### Working Principle of Queues in my Application**

--> Here, in my FreeRTOS application, I am using Queues to establish Intertask communication between Fingerprint sensor and Temperature sensor

-->  I implemented FreeRTOS queue functions namely xQueueSend and xQueueReceive to acquire 10 sensor readings in my xQueueSend function of Temperature task and then transfer those readings through Fingerprint task only when my Fingerprint is matched

**Comment by atharvdesai1996** [comment]
### **Importance of xQueueReset**


I realized that I will have to use xQueueReset function too to make my queue hold the most recent 10 temperature readings.

I have attached the screenshots of both :    

![q_reset_imp](https://user-images.githubusercontent.com/49723941/80304519-b66ff200-8773-11ea-8d89-af455f37a138.JPG)

--> Without xQueueReset where my queue gets full quickly with first 10 readings and of temperature sensor and feeds old readings only to the Fingerprint task xQueueReceive Function

 
![withqueue_reset-imp2](https://user-images.githubusercontent.com/49723941/80304524-d4d5ed80-8773-11ea-9e7d-5b1df1b19c8b.JPG)

--> Using xQueueReset , my queue is able to hold the most recent  value of temperature in the queue and as soon as the Fingerprint is matched the value gets sent to UART through my xQueueReceive Function

**Comment by aakshajaywant** [comment]
**### Semaphore Locking Mechanism Implementation**

--> Implemented locking mechanism using semaphores. 

--> It involves xSemaphoreTake and xSemaphoreGive. 

--> Earlier I was using a global flag to indicate that the fingerprint is matched used in the fingerprint task to send temperature readings to the server. 

--> Therefore, the critical section was protected by replacing my 'fmatchflag' in the screenshots below by Semaphore 
![sema1](https://user-images.githubusercontent.com/49723941/80336232-eec70d00-8813-11ea-84d8-198f9b99c4e9.JPG)
![sema2](https://user-images.githubusercontent.com/49723941/80336233-ef5fa380-8813-11ea-8603-85794a6daa72.JPG)


[Code](https://github.com/cu-ecen-5013/final-project-ruchaborwankar/tree/5780f36c80bd7fce4178f6543164543b027bc1ac)
