### ISSUE TITLE
Validation and Testing 

### ISSUE THREAD

**Issue by ruchaborwankar** [cu-ecen-5013/final-project-atharvdesai1996#12]
ToDo: To ensure smooth functioning of server and client and data flow throughout the system.

DoD:
Testing and validating the corner cases on the server and client side.

**Comment by atharvdesai1996** [comment]
--> We tested out the corner cases for Fingerprint interrupt generation from one  Tiva Client and synchronizing with the other Tiva Client for Ultrasound sensor reception on the client side

--> Verified the Robustness of the system by checking the proper hardware integration 

--> Tested whether the alteration of the sequence of sensor data acquisition fetch valid data on the server
