### ISSUE TITLE
Developing FreeRTOS Application to handle TMP-102 and Fingerprint Sensor tasks

### ISSUE THREAD

**Issue by atharvdesai1996** [cu-ecen-5013/final-project-atharvdesai1996#8]
ToDo: Developing FreeRTOS Application to handle TMP-102 and Fingerprint Sensor tasks

DoD:  The FreeRTOS application should be able to schedule two tasks of acquiring the TMP-102 sensor reading and Fingerprint sensor interrupt and sending the appropriate temperature sensor readings to the BeagleBone Server once the car owner's Fingerprint is matched

**Comment by atharvdesai1996** [comment]
I was facing this eccentric issue as seen in the screenshot that my UART 3 pins weren't shown as defined. Even though, pin_map.h header file had the initializations, I wasn't able to figure out the issue even though the required libraries were included. So, finally I directly defined those macros mapped with the addresses in pin_map.h


![freertosdoubt1](https://user-images.githubusercontent.com/49723941/79953827-b7ceb100-8439-11ea-8d05-71a8afaa1a49.JPG)

### **Solution:** 

![freertosdoubt2](https://user-images.githubusercontent.com/49723941/79954709-eef19200-843a-11ea-9472-15adc7baaf40.JPG)

**Comment by atharvdesai1996** [comment]
**### **### Result****
The code uploaded is able to schedule two tasks , TMP102 sensor reading reception task and the Fingerprint sensor matched/ not matched status checking task

[Code](https://github.com/cu-ecen-5013/final-project-atharvdesai1996/tree/9502478b289d2b8a569a4f6877f5129086358841)

![queue_functional](https://user-images.githubusercontent.com/49723941/80337436-0eac0000-8817-11ea-8f52-6ed2774a2d94.JPG)


--> The Screenshot shows that the data i.e the 10 temperature sensor readings are being transmitted to the BeagleBone Server on UART 4 of Tiva client

**Comment by aakshajaywant** [comment]
### **### Result**

--> Below shows the output of the Set up of Client 1 TIVA. I integrated two sensors namely the Fingerprint and the Temperature Sensor 

-->  I have gotten the FreeRTOS  Schedular running and functional with required Queue Implementation and Locking Mechanism to increase the robustness and handle the Worst Case Scenarios

![IMG_20200426_224432](https://user-images.githubusercontent.com/55064839/80334953-0a301900-8810-11ea-8ead-5202c00f57e3.jpg)

Below is the Code Link
[Code](https://github.com/cu-ecen-5013/final-project-ruchaborwankar/tree/5780f36c80bd7fce4178f6543164543b027bc1ac)
