### ISSUE TITLE
Designing a Logging System on BeagleBone Client with Timestamps

### ISSUE THREAD

**Issue by atharvdesai1996** [cu-ecen-5013/final-project-atharvdesai1996#9]
ToDo:  Designing a Logging System on BeagleBone Client with Timestamps

DoD: The sensor data  received from the BeagleBone Server should be logged by client by storing it in file with timestamps

**Comment by aakshajaywant** [comment]
**### Features**

1) Beaglebone client is now able to receive data from the beaglebone server. 

2) This data is getting logged in /tmp/temperature and /tmp/ultrasonic with timestamps

3) Also, I'm printing the received sensor data mapped to its timestamp on the Buildroot Terminal

**Comment by aakshajaywant** [comment]
**### LOG Files for Temperature and Ultrasonic Sensor**

Below output shows the readings from the server:
1) Temperature values received from the server with timestamps

![logtemperature](https://user-images.githubusercontent.com/49723941/80335666-3c427a80-8812-11ea-9b70-395b59910b78.JPG)


2) Ultrasonic values received from the server with timestamps

![logultrasonic](https://user-images.githubusercontent.com/49723941/80335716-63994780-8812-11ea-8ed2-774df787184c.JPG)

**Comment by aakshajaywant** [comment]
### **### Printing on the Terminal with Timestamp Mapping**

Also, I printed the Temperature and Fingerprint values on the Buildroot Terminal

![logfpmes_uwork_prt1](https://user-images.githubusercontent.com/49723941/80335857-c854a200-8812-11ea-84d9-5ba129dd8d92.JPG)



[Code Link](https://github.com/cu-ecen-5013/final-project-atharvdesai1996/tree/1bf528acc6b9f3052953f6f4ed6ab3f19accfc21)
